metrics_server:
  enabled: True

dashboard:
  enabled: True

metallb:
  enabled: False
  addresses: "192.168.0.1-192.168.0.2"

default_ingress_class: "nginx"

cert_manager:
  enabled: False
  email: "admin@maia.se"