apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-role
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
rules:
  - verbs:
      - '*'
    apiGroups:
      - '*'
    resources:
      - services
      - ingresses
      - pods/portforward
      - deployments/scale
      - pods/log
      - pods
      - secrets
      - persistentvolumeclaims
      - pods/exec
      - deployments
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-role-binding
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: "MAIA:"{{ .Values.groupName }}
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-role
