# Default values for maia-namespace.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
pvc:
  pvc_type: "standard"
  access_mode: "ReadWriteOnce"
  size: "1Gi"

namespace: "maia"