{{- range .Values.users }}
apiVersion: v1
kind: Service
metadata:
  name: jupyter-{{ .jupyterhub_username }}
spec:
  ports:
    - name: remote-desktop-port
      protocol: TCP
      port: 80
      targetPort: 80
    - name: jupyter-port
      protocol: TCP
      port: 8888
      targetPort: 8888
  selector:
    hub.jupyter.org/username: {{ .jupyterhub_username }}
---
{{- end}}