{{- if .Values.traefik.enabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: auth
spec:
  forwardAuth:
    address: https://{{ .Values.oauth_url }}/oauth2
    authResponseHeaders:
      - X-Auth-Request-Access-Token
      - Authorization
    trustForwardHeader: true
{{- end }}
