{{- range .Values.users }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .jupyterhub_username }}-ssh
  annotations:
    metallb.universe.tf/allow-shared-ip: {{ $.Values.metallb.shared_ip }}
    metallb.universe.tf/ip-allocated-from-pool: {{ $.Values.metallb.ip_pool }}
spec:
  ports:
    - name: ssh
      protocol: TCP
      port: {{ .ssh_port}}
      targetPort: 2022
      {{- if eq $.Values.ssh_port_type "NodePort" }}
      nodePort: {{ .ssh_port }}
      {{- end }}
  selector:
    hub.jupyter.org/username: {{ .jupyterhub_username }}
  type: {{ $.Values.ssh_port_type }}
---
{{- end }}