version: '3.8'

services:
  workspace:
    image: maia-workspace-notebook-ssh-addons:1.6b
    ports:
      - "8082:8082"
      - "8888:8888"
    command: 
      - jupyter 
      - lab
      - --ip=0.0.0.0
    environment:
      - JUPYTERHUB_USER=test@maia.se
      - PASSWD=maia
      - NB_USER=maia-user
      - GRANT_SUDO=yes
      - SHELL=/usr/bin/zsh
      - TZ=UTC
      - SIZEW=1920
      - SIZEH=1080
      - REFRESH=60
      - DPI=96
      - CDEPTH=24
      - WEBRTC_ENCODER=nvh264enc
      - BASIC_AUTH_PASSWORD=maia
      - NOVNC_ENABLE=true
      - ssh_publickey=NOKEY
      - MINIO_ACCESS_KEY=N/A
      - MINIO_SECRET_KEY=N/A
      - MLFLOW_TRACKING_URI=https://maia.se/mlflow
      - HOSTNAME=maia
      - NAMESPACE=maia
      - SSH_PORT_test__at__maia.se=22
      - INSTALL_ZSH=1
      - INSTALL_ITKSNAP=1
      - CONDA_ENVS_PATH=/home/maia-user/.conda/envs/


