{{- if .Values.argocd.additional_clusters }}
{{- range .Values.argocd.additional_clusters }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}-cluster
  namespace: {{ $.Values.argocd.argocd_namespace }}
  labels:
    argocd.argoproj.io/secret-type: cluster
data:
  name: {{ .name | b64enc }}
  server: {{ .server | b64enc }}
  {{- if .token }}
  config: {{ printf "{\"bearerToken\":\"%s\",\"tlsClientConfig\":{\"insecure\":true}}" .token | b64enc }}
  {{- else }}
  config: {{ "{\"tlsClientConfig\":{\"insecure\":true}}" | b64enc }}
  {{- end }}

type: Opaque
{{- end }}
{{- end }}