apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-role-admin
rules:
  - verbs:
      - '*'
    apiGroups:
      - '*'
    resources:
      - '*'
  - verbs:
      - get
      - watch
      - list
    nonResourceURLs:
      - '*'
  - verbs:
      - create
    apiGroups:
      - ''
    resources:
      - pods/exec
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-role-read
rules:
  - verbs:
      - get
      - list
    apiGroups:
      - '*'
    resources:
      - namespaces
      - nodes
      - pods
      - services
      - ingresses
