{{- if .Values.harbor.enabled}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-harbor
  namespace: {{ .Values.harbor.values.namespace }}
spec:
  storageClassName: {{ .Values.harbor.values.storageClassName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
{{- end}}