{{- if .Values.minio.enabled }}
apiVersion: v1
data:
  CONSOLE_ACCESS_KEY: {{ .Values.minio.consoleAccessKey | b64enc }}
  CONSOLE_SECRET_KEY: {{ .Values.minio.consoleSecretKey | b64enc }}
kind: Secret
metadata:
  name: storage-user
  namespace: {{ .Values.minio.namespace }}
type: Opaque
{{- end }}