{{- if .Values.minio.enabled }}
apiVersion: v1
data:
  CONSOLE_ACCESS_KEY: {{ .Values.minio.consoleAccessKey }}
  CONSOLE_SECRET_KEY: {{ .Values.minio.consoleSecretKey }}
kind: Secret
metadata:
  name: storage-user
  namespace: {{ .Values.minio.namespace }}
type: Opaque
{{- end }}