{{- if .Values.minio.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: storage-configuration
  namespace: {{ .Values.minio.namespace }}
stringData:
  config.env: |
    export MINIO_BROWSER=on
    export MINIO_IDENTITY_OPENID_CLIENT_SECRET={{ .Values.minio.clientSecret }}
    export MINIO_IDENTITY_OPENID_CLAIM_NAME=groups
    export MINIO_IDENTITY_OPENID_SCOPES=email,openid,profile
    export MINIO_ROOT_USER={{ .Values.minio.accessKey }}
    export MINIO_ROOT_PASSWORD={{ .Values.minio.secretKey }}
    export MINIO_IDENTITY_OPENID_CONFIG_URL={{ .Values.minio.openIdConfigUrl }}
    export MINIO_IDENTITY_OPENID_CLIENT_ID={{ .Values.minio.clientId }}
    export MINIO_IDENTITY_OPENID_DISPLAY_NAME=MAIA
type: Opaque
{{- end }}
