{{- range .Values.users }}
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: {{ .user}}-secret-propagation
spec:
  resourceSelectors:
    - apiVersion: v1
      kind: Secret
      name: user-{{ .user}}-secret
  placement:
    clusterAffinity:
      clusterNames:
        {{- toYaml $.Values.secret_clusters | nindent 8 }}
---
{{- end}}
