{{- if .Values.ingress.nginx.enabled}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: "{{ .Values.ingress.nginx_issuer }}"
    nginx.ingress.kubernetes.io/proxy-body-size: 500m
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/auth-signin: https://{{$.Values.ingress.oauth_url}}/oauth2/start?rd=https://$host$uri
    nginx.ingress.kubernetes.io/auth-url: http://oauth2-proxy.{{$.Values.namespace}}.svc.cluster.local:80/oauth2/auth
  name: {{ include "hive.fullname" $ }}{{"-ingress"}}
  namespace: {{ .Release.Namespace }}
spec:
  rules:
    - host: {{ .Values.ingress.host}}
      http:
        paths:
          - pathType: Prefix
            path: /{{ .Values.ingress.path}}
            backend:
              service:
                name: {{ include "hive.fullname" . }}
                port:
                  number: {{ .Values.ingress.port | int }}
  tls:
    - hosts:
        - {{ .Values.ingress.host}}
      secretName: {{ include "hive.fullname" $ }}{{"-ingress"}}-tls
  {{- end }}