{{- if .Values.deploy_as_job }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "hive.fullname" . }}
  labels:
  {{- include "hive.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  ttlSecondsAfterFinished: 0
  backoffLimit: 0
  activeDeadlineSeconds: {{.Values.allocatedTime}}
  {{- end }}
  #selector:
  #  matchLabels:
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
    {{- include "hive.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
         {{- if .Values.persistentVolume}}
        {{- range $i, $s := .Values.persistentVolume}}
        - name: hive-persistent-storage-{{$i}}
          persistentVolumeClaim:
            claimName: {{ include "hive.fullname" $ }}{{"-claim-"}}{{$i}}
         {{- end}}
        {{- end}}
        {{- if .Values.secretCSIVolume}}
        {{- range $i, $s := .Values.secretCSIVolume}}
        - name: csi-secret-{{$i}}
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ .name }}
        {{- end}}
        {{- end}}
        {{- if .Values.existingPersistentVolume}}
        {{- range $i, $s := .Values.existingPersistentVolume}}
        - name: hive-existing-persistent-storage-{{$i}}
          persistentVolumeClaim:
            claimName: {{ .name }}
         {{- end}}
        {{- end}}
        {{- if .Values.dshm}}
        - name: dshm
          emptyDir:
            medium: Memory
        {{- end}}
        {{- range .Values.extraSecretVolumes }}
        - name: {{ .name | quote }}
          secret:
            secretName: {{ .secretName | quote }}
        {{- end}}
        {{- range .Values.extraNFSVolumes }}
        - name: {{ .name | quote }}
          nfs:
            path: {{ .hostPath | quote }}
            server: {{ .server | quote }}
      {{- end }}
      {{- range .Values.extraHostVolumes }}
        - name: {{ .name | quote }}
          hostPath:
            path: {{ .hostPath | quote }}
            {{- end }}
      {{- range .Values.extraConfigMapVolumes }}
        - name: {{ .name | quote }}
          configMap:
            name: {{ .configMapName | quote }}
            items:
              - key: {{ .configMapFile | quote }}
                path: {{ .configMapPath | quote }}
                 {{- end }}
      securityContext:
      {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- if (.Values.gpus) }}
            {{ else}}
            - name: NVIDIA_VISIBLE_DEVICES
              value: ""
            {{- end}}
            {{- if .Values.extraEnv }}
          {{- toYaml .Values.extraEnv | nindent 12 }}
          {{- end }}
          {{- if .Values.resources}}
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.command }}
          command:
          {{- toYaml .Values.command | nindent 12  }}
            {{- end }}
          {{- if .Values.args}}
          args:
            {{- toYaml .Values.args | nindent 12}}
          {{- end}}
          {{- if .Values.extraVolumeMounts }}
          volumeMounts:
            {{- if .Values.persistentVolume}}
            {{- range $i, $s := .Values.persistentVolume}}
            - name: hive-persistent-storage-{{$i}}
              mountPath: {{ .mountPath }}
            {{- end}}
            {{- end}}
            {{- if .Values.existingPersistentVolume}}
            {{- range $i, $s := .Values.existingPersistentVolume}}
            - name: hive-existing-persistent-storage-{{$i}}
              mountPath: {{ .mountPath }}
            {{- end}}
            {{- end}}
          {{- toYaml .Values.extraVolumeMounts | nindent 12 }}
      {{- end }}
      {{- if  or (.Values.gpuSelected)  (.Values.nodeSelected) }}
      nodeSelector:
              {{- if .Values.nodeSelected}}
        "kubernetes.io/hostname": {{ .Values.nodeSelected}}
        {{- end}}
        {{- if .Values.gpuSelected}}
        {{- if .Values.gpuSelected.type}}
        "gpu.type": {{ .Values.gpuSelected.product}}
        {{- end}}
        {{- end}}
        {{- end}}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
  {{- end }}
{{- if .Values.persistentVolume}}
{{- range $i, $s := .Values.persistentVolume}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "hive.fullname" $ }}{{"-claim-"}}{{$i}}
  labels:
    {{- include "hive.selectorLabels" $ | nindent 6 }}
spec:
  {{- if .pvc_type}}
  storageClassName: {{ .pvc_type }}
  {{- end}}
  {{- if .access_mode}}
  accessModes:
    - {{ .access_mode}}
    {{- end}}
  resources:
    requests:
      storage: {{ .size }}
  {{- end }}
  {{- end }}
    {{- end}}