argocd: 
  enabled: true
  argocd_namespace: "argocd"
  argocd_domain: ""
  keycloak_issuer_url: ""
  keycloak_client_id: ""
  keycloak_client_secret: ""
## Additional clusters to be added to ArgoCD
#  additional_clusters: 
#    - name: "fake-cluster"
#      server: "https://kubernetes.default.svc"
#      token: "fake-token"
certResolver: ""
admin_group_ID: "MAIA:admin"

harbor: 
  enabled: true
  values: 
    namespace: ""
    storageClassName: 

dashboard: 
  enabled: true
  dashboard_domain: ""


