argocd: 
  enabled: true
  argocd_namespace: "argocd"
  argocd_domain: ""
  keycloak_issuer_url: ""
  keycloak_client_id: ""
  keycloak_client_secret: ""
certResolver: ""
admin_group_ID: "MAIA:admin"

harbor: 
  enabled: true
  values: 
    namespace: ""
    storageClassName: 

dashboard: 
  enabled: true
  dashboard_domain: ""


